target: pl_modules.itransformer_module.iTransformerModule
params:
    num_features: 5
    seq_len: 14
    use_norm: True
    d_model: 128
    d_ff: 128
    dropout: 0
    activation: 'gelu'
    e_layers: 2
    output_attention: True
    factor: 1
    n_heads: 16
    loss: 'mse'
normalize: False